Creating a main page (client)
iSharovatov1/newsSiteFront pull request #2
Opened 2022-06-21 09:01 UTC by iSharovatov1

2022-06-22 06:57 UTC, peterdee requested changes

2022-06-22 06:57 UTC, peterdee commented on src/App.module.scss
> +
Remove empty spaces

2022-06-22 06:57 UTC, peterdee commented on src/App.js
> +import { News } from './components/News'
There should not be an empty line between the local imports:

```javascript
import { News } from './components/News';
import styles from './App.module.scss';
```

2022-06-22 06:57 UTC, peterdee commented on src/components/News/News.module.scss
> +
Remove empty line

2022-06-22 06:57 UTC, peterdee commented on src/components/News/index.js
> +export const News = () => {
Use `React.memo()` for performance optimization

2022-06-22 06:57 UTC, peterdee commented on src/components/News/index.js
> +  const news = useSelector(state => state.news);
Wrap lambda function arguments:

```javascript
const news = useSelector((state) => state.news);
```

2022-06-22 06:57 UTC, peterdee commented on src/components/News/index.js
> +      )}
Missing `key` prop.

Missing wraps for function arguments.

Missing wraps for JSX.

This is how it should look like:

```javascript
      {news?.map((item) => (
        <div
          className={styles.news}
          key={item.id}
        >
          <div className={styles.title}>{item.title}</div>
          <div className={styles.text}>{item.text}</div>
        </div>
      ))}
```

2022-06-22 06:57 UTC, peterdee commented on src/store/actions.js
> +  }
Rewrite completely.

You don't need to use `then` when you have `await`.

`data` should be a constant.

```javascript
const { data } = await axios({ ... });
return data;
```

2022-06-22 06:57 UTC, peterdee commented on src/store/reducer.js
> +import { GET_USERS } from "./constants";
Use single quotes instead of double quotes

2022-06-28 14:09 UTC, tatiana-dunice requested changes

2022-07-12 09:11 UTC, tatiana-dunice requested changes

2022-07-12 09:11 UTC, tatiana-dunice commented on src/store/actions.js
> +const getNews = { type: 'NEWS_FETCH_REQUESTED' };
```
import { createAction } from 'redux-actions';

import actionTypes from '../../constants/actionTypes';

export const getNews = createAction(
  actionTypes.NEWS_FETCH_REQUESTED,
);

```

2022-07-12 09:11 UTC, tatiana-dunice commented on src/store/index.js
>  import mySaga from './sagas';
Might be rootSaga? it doesn't clear what is `mySaga`

2022-07-12 09:11 UTC, tatiana-dunice commented on src/store/actions.js
> +const getNews = { type: 'NEWS_FETCH_REQUESTED' };
- f store
   - index.js
   - f actions
      - newsActions.js
   - f reducers
       - index.js (combinedReducer)
       - newsReducer.js
   - f sagas
       - index.js (rootSaga)
       - newsSaga.js

2022-07-12 09:11 UTC, tatiana-dunice commented on src/store/reducer.js
> +  error: '',
in case of setting error as empty string you need to check it obviouse everywhere: `error !== ''`

2022-07-12 09:11 UTC, tatiana-dunice commented on src/store/reducer.js
> +      news: action.news,
action.payload

2022-07-12 09:11 UTC, tatiana-dunice commented on src/store/reducer.js
> +    case 'NEWS_FETCH_REQUESTED': return { ...state, loading: true, error: '' };
yse constants for cases

2022-07-12 09:11 UTC, tatiana-dunice commented on src/store/sagas.js
> +    yield put({ type: 'NEWS_FETCH_SUCCEEDED', news });
use actions here (from actions folder)

2022-07-12 09:11 UTC, tatiana-dunice commented on src/store/sagas.js
> +import { call, put, takeEvery } from 'redux-saga/effects';
An empty line is required after packages imports

2022-07-14 11:37 UTC, tatiana-dunice requested changes

2022-07-18 08:31 UTC, tatiana-dunice commented on src/store/sagas/newsSaga.js
> +import getNews from '../../api/newsApi';
`import getNews from '../../api/newsApi';` - suppose that this file would have more than one method

2022-07-18 08:32 UTC, tatiana-dunice commented on src/store/sagas/newsSaga.js
> +    const news = yield call(getNews, action.payload);
You can destructurize action - `fetch...({ payload })`

2022-07-18 10:51 UTC, tatiana-dunice approved these changes

2022-07-18 10:51 UTC, merged