add user page
iSharovatov1/newsSiteFront pull request #4
Opened 2022-07-25 08:44 UTC by iSharovatov1

# [newsSiteFront](https://github.com/iSharovatov1/newsSiteFront)
> Creating a user page (server + client)
### Code Details
* add user page
* ### Screenshots
![2022-07-25_11-26](https://user-images.githubusercontent.com/107611857/180736059-a1414760-9df3-4994-8fd4-4166db9687b7.png)
![2022-07-25_11-27](https://user-images.githubusercontent.com/107611857/180736079-8ed8a241-472b-463f-b4e3-d32c6f5ade3d.png)
### Feature tag selection
Has a `Creating a user page (server + client)`  Has it been added [to the tracker](https://trello.com/b/EICN697S/%D1%88%D0%B0%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D0%BE%D0%B2%D0%B8%D0%B3%D0%BE%D1%80%D1%8C%D0%BD%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D0%BD%D0%BE%D0%B9%D1%81%D0%B0%D0%B9%D1%82)?

2022-07-25 09:03 UTC, tatiana-dunice requested changes

2022-07-25 09:03 UTC, tatiana-dunice commented on src/store/reducers/userReducer.js
> +      return { ...state, loading: true, error: null };
you're using the same loading field for sevaral requests - can couse an issue

2022-07-25 09:19 UTC, iSharovatov1 commented on src/api/newsApi.js
> +  const { data } = await instance.get('/news');
I changed path in env

2022-07-25 10:14 UTC, tatiana-dunice commented on src/api/newsApi.js
> +  const { data } = await instance.get('/news');
got it

2022-07-25 12:29 UTC, tatiana-dunice requested changes

2022-07-25 14:14 UTC, tatiana-dunice requested changes

2022-07-26 09:40 UTC, tatiana-dunice requested changes

2022-07-26 09:40 UTC, tatiana-dunice commented on src/api/instance.js
>    baseURL: process.env.REACT_APP_BASE_URL,
why did you remove `withCredentials`?

2022-07-26 09:40 UTC, tatiana-dunice commented on src/components/NewsCard/NewsCard.jsx
> +  const defaultImg = '/assets/images/defaultImg.png';
use it in place or move outside the component - and change name - it's a constant

2022-07-26 09:40 UTC, tatiana-dunice commented on src/components/NewsCard/NewsCard.jsx
> +      { isLoading
You can avoid this internal conditions by moving it outside

2022-07-26 09:40 UTC, tatiana-dunice commented on src/components/NewsCard/NewsCard.module.scss
> +      .autor {
redundant style - remove it

2022-07-27 06:53 UTC, tatiana-dunice requested changes

2022-07-27 06:53 UTC, tatiana-dunice commented on src/components/NewsCard/NewsCard.jsx
> +  onClick: () => null,
`() => null,` -> `() => {},`

2022-07-27 06:53 UTC, tatiana-dunice commented on src/components/UserProfile/UserProfile.module.scss
> +}
New line is required

2022-07-29 11:11 UTC, tatiana-dunice approved these changes

2022-07-29 11:11 UTC, merged